# Generated by Django 4.2.1 on 2023-07-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='Sdesc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Semail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Sname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='Sphone',
        ),
    ]
