# Generated by Django 4.2.1 on 2023-07-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_rename_desc_contact_sdesc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Sdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Semail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Sname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Sphone',
            new_name='phone',
        ),
    ]
