# Generated by Django 4.2.1 on 2023-07-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_alter_contact_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(max_length=10),
        ),
    ]
