# Generated by Django 4.2.1 on 2023-07-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_alter_contact_id_alter_login_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactModel',
        ),
    ]
