# Generated by Django 4.2.1 on 2023-07-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_rename_contact_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
