# Generated by Django 4.2.1 on 2023-07-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_alter_contactmodel_email_alter_contactmodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=50)),
                ('Fname', models.CharField(max_length=50)),
                ('Mname', models.CharField(max_length=50)),
                ('Semail', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('caste', models.CharField(max_length=10)),
                ('Sphone', models.CharField(max_length=12)),
                ('Sclname', models.CharField(max_length=100)),
                ('Marks1', models.FileField(upload_to='')),
                ('Clgname', models.CharField(max_length=100)),
                ('Marks2', models.FileField(upload_to='')),
                ('Marks3', models.FileField(upload_to='')),
                ('Emrank', models.FileField(upload_to='')),
            ],
        ),
    ]
