# Generated by Django 4.2.1 on 2023-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_meritmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('semail', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('caste', models.CharField(max_length=3)),
                ('sphone', models.CharField(max_length=12)),
                ('sport', models.CharField(max_length=30)),
                ('aname', models.CharField(max_length=100)),
                ('authority', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('disabilities', models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Clgname',
            new_name='clgname',
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Emrank',
            new_name='emrank',
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Fname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Marks1',
            new_name='marks1',
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Marks2',
            new_name='marks2',
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Marks3',
            new_name='marks3',
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Mname',
            new_name='mname',
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Sclname',
            new_name='sclname',
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Semail',
            new_name='semail',
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Sname',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='meritmodel',
            old_name='Sphone',
            new_name='sphone',
        ),
    ]
