# Generated by Django 4.2.1 on 2023-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_rename_aname_athleticmodel_academy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('focc', models.CharField(max_length=100)),
                ('mocc', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('caste', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=12)),
                ('sclname', models.CharField(max_length=100)),
                ('clgname', models.CharField(max_length=100)),
                ('income', models.FileField(upload_to='')),
            ],
        ),
    ]
