# Generated by Django 4.2.1 on 2023-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_economicalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merit_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=122)),
                ('service_amount', models.CharField(max_length=122)),
                ('service_eligibility', models.CharField(max_length=122)),
            ],
        ),
    ]
