# Generated by Django 4.2.1 on 2023-07-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_merit_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service1_logo', models.CharField(max_length=100)),
                ('service1_name', models.CharField(max_length=122)),
                ('service1_amount', models.CharField(max_length=122)),
                ('service1_eligibility', models.CharField(max_length=122)),
            ],
        ),
    ]
