# Generated by Django 4.2.1 on 2023-07-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_sport_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport_services',
            name='service1_logo',
        ),
    ]
