# Generated by Django 4.2.1 on 2023-07-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0018_economical_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='economical_services',
            old_name='service3_eligibility',
            new_name='service2_eligibility',
        ),
    ]
